/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import static org.junit.Assert.*;

import java.util.LinkedList;

import org.junit.Test;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals("こんにちは SEMonster", classUnderTest.getGreeting());
    }

    @Test
    public void testCreateRandomList() {
        LinkedList<Integer> list = App.createRandomList(10);
        assertEquals(10, list.size());

        for (int i=0; i<10; i++) {
            assertTrue(list.get(i) >= 0);
            assertTrue(list.get(i) <= 4);
        }
    }
}
