/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals("こんにちは SEMonster", classUnderTest.getGreeting());
    }
}
